[workspace]
members=[
     #basics
    "basic/account-data/native/program",
    "basic/account-data/account-data-anchor-program-example/programs/account-data-anchor-program-example",
    
    
]
resolver = "2"